- name: Install and configure Jenkins on Linux
  hosts: jenkins
  become: true
  tasks:
    # First remove Java 11 if installed
    - name: Remove Java 11
      apt:
        name: 
          - openjdk-11-jdk
          - openjdk-11-jdk-headless
          - openjdk-11-jre
          - openjdk-11-jre-headless
        state: absent
        autoremove: yes

    # Install Java 17
    - name: Install Java 17
      apt:
        name: 
          - openjdk-17-jdk
          - openjdk-17-jre
        state: present
        update_cache: yes

    # Find Java home
    - name: Find Java installation path
      shell: readlink -f /usr/bin/java | sed "s:/bin/java::"
      register: java_path
      changed_when: false

    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME={{ java_path.stdout }}'
        state: present

    # Jenkins repository setup
    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /tmp/jenkins.io-2023.key
        mode: '0644'

    - name: Import Jenkins GPG key
      apt_key:
        file: /tmp/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins
        update_cache: yes

    # Install Jenkins
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    # Set permissions
    - name: Set Jenkins directory permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
        recurse: yes
      with_items:
        - /var/lib/jenkins
        - /var/cache/jenkins
        - /var/log/jenkins

    # Configure Jenkins defaults
    - name: Configure Jenkins defaults
      lineinfile:
        path: /etc/default/jenkins
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: yes
      with_items:
        - regexp: '^JENKINS_HOME='
          line: 'JENKINS_HOME=/var/lib/jenkins'
        - regexp: '^JENKINS_USER='
          line: 'JENKINS_USER=jenkins'
        - regexp: '^JENKINS_JAVA_OPTIONS='
          line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Xmx512m"'
        - regexp: '^JAVA_HOME='
          line: 'JAVA_HOME={{ java_path.stdout }}'
    - name: Ensure the jenkins service environment variables
      systemd:
          name: jenkins
          state: stopped
    - name: Create systemd dropin directory
      file:
        path: /etc/systemd/system/jenkins.service.d
        state: directory
        mode: '0755'
    - name: Create systemd dropin for environment variables
      file:
        path: /etc/systemd/system/jenkins.service.d/env.conf
        state: touch
    - name: Create systemd dropin for environment variables
      blockinfile:
        path: /etc/systemd/system/jenkins.service.d/env.conf
        create: yes
        block: |
          [Service]
          Environment=JAVA_HOME={{ java_path.stdout }}
    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: restarted
        daemon_reload: yes
        enabled: yes

    # Wait for Jenkins to start
    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 30
        timeout: 300

    # Allow Jenkins through firewall
    - name: Allow Jenkins port through UFW
      ufw:
        rule: allow
        port: 8080
        proto: tcp
      when: ansible_os_family == "Debian"