# tools/jenkins/values.yaml
controller:
  installPlugins:
    - kubernetes:latest
    - configuration-as-code:latest
    - workflow-aggregator:latest
    - git:latest
    - hashicorp-vault-plugin:latest
    - credentials-binding:latest
  JCasC:
    configScripts:
      jenkins-auth: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin@123"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      id: "vault-token"
                      secret: ${VAULT_TOKEN}
                      description: "Vault Token"
      vault: |
        unclassified:
          hashicorpVault:
            configuration:
              vaultUrl: "http://vault.security-tools.svc.cluster.local:8200"
              vaultCredentialId: "vault-token"
              engineVersion: 2
  extraEnv:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-vault-token
          key: token
  serviceType: LoadBalancer
  loadBalancerIP: "192.168.5.241"

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce