controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"

  installPlugins:
    - kubernetes:latest
    - git:latest
    - configuration-as-code:latest
    - workflow-aggregator:latest
    - sonar:latest
    - pipeline-utility-steps:latest
    - workflow-multibranch:latest

  env:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-sonar-token
          key: token

  JCasC:
    configScripts:
      jenkins-auth: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin@123"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

      sonar: |
        unclassified:
          sonarGlobalConfiguration:
            buildWrapperEnabled: true
            installations:
              - name: "SonarQube"
                serverUrl: "http://sonarqube-sonarqube.devsecops:9000"
                credentialsId: "sonar-token"

      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      id: "sonar-token"
                      secret: ${SONAR_TOKEN}
                      scope: GLOBAL
                      description: "SonarQube Token"

      clouds: |
        jenkins:
          clouds:
            - kubernetes:
                containerCap: 10
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                namespace: "devsecops"
                skipTlsVerify: true
                jenkinsUrl: "http://jenkins.devsecops:8080"
                jenkinsTunnel: "jenkins-agent.devsecops:50000"
                templates:
                  - name: "jenkins-agent"
                    label: "jenkins-agent"
                    nodeUsageMode: NORMAL
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        alwaysPullImage: true
                        workingDir: "/home/jenkins/agent"
                        resourceRequestCpu: "500m"                      

  serviceType: LoadBalancer
  loadBalancerIP: "192.168.5.241"

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce