# tools/jenkins/values.yaml
controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"
  installPlugins:
    - kubernetes:latest
    - git:latest
    - configuration-as-code:latest
    - workflow-aggregator:latest
    - sonar:latest
    - pipeline-utility-steps:latest
    - workflow-multibranch:latest
    - hashicorp-vault-plugin:latest
    - credentials-binding:latest
  JCasC:
    configScripts:
      jenkins-auth: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin@123"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      id: "sonar-token"
                      secret: ${SONAR_TOKEN}
                      scope: GLOBAL
                      description: "SonarQube Token"
                  - string:
                      id: "vault-token"
                      secret: ${VAULT_TOKEN}
                      scope: GLOBAL
                      description: "Vault Root Token"
      vault: |
        unclassified:
          hashicorpVault:
            configuration:
              vaultUrl: "http://vault.security-tools.svc.cluster.local:8200"
              vaultCredentialId: "vault-token"
              engineVersion: 2
              skipSslVerification: true
      sonar: |
        unclassified:
          sonarGlobalConfiguration:
            buildWrapperEnabled: true
            installations:
              - name: "SonarQube"
                serverUrl: "http://sonarqube-sonarqube.devsecops:9000"
                credentialsId: "sonar-token"
  extraEnv:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-sonar-token
          key: token
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-vault-token
          key: token
  serviceType: LoadBalancer
  loadBalancerIP: "192.168.5.241"

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce