controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"

  installPlugins:
    - kubernetes:latest
    - git:latest
    - configuration-as-code:latest
    - workflow-aggregator:latest
    - sonar:latest
    - pipeline-utility-steps:latest
    - workflow-multibranch:latest
    - hashicorp-vault-plugin:latest
    - credentials-binding:latest

  env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-vault-token
          key: token
    - name: VAULT_ADDR
      value: "http://vault.security-tools.svc.cluster.local:8200"

  JCasC:
    configScripts:
      jenkins-auth: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin@123"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

      vault: |
        unclassified:
          hashicorpVault:
            configuration:
              engineVersion: 2
              skipSslVerification: true
              timeout: 60
              vaultCredential:
                id: "vault-token"
                scope: GLOBAL
                description: "Vault Token"
                secret: ${VAULT_TOKEN}
              vaultUrl: "http://vault.security-tools.svc.cluster.local:8200"

      sonar: |
        unclassified:
          sonarGlobalConfiguration:
            buildWrapperEnabled: true
            installations:
              - name: "SonarQube"
                serverUrl: "http://sonarqube-sonarqube.devsecops:9000"
                credentialsId: "sonar-token"

      credentials: |
        credentials:
          system:
            domainCredentials:
              - domain:
                  name: "global"
                  description: "Global credentials"
                credentials:
                  - string:
                      id: "sonar-token"
                      secret: ${SONAR_TOKEN}
                      scope: GLOBAL
                      description: "SonarQube Token"
                  - string:
                      id: "vault-token"
                      secret: ${VAULT_TOKEN}
                      scope: GLOBAL
                      description: "Vault Token"

      clouds: |
        jenkins:
          clouds:
            - kubernetes:
                containerCap: 10
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                namespace: "devsecops"
                skipTlsVerify: true
                jenkinsUrl: "http://jenkins.devsecops:8080"
                jenkinsTunnel: "jenkins-agent.devsecops:50000"
                templates:
                  - name: "jenkins-agent"
                    label: "jenkins-agent"
                    nodeUsageMode: NORMAL
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        alwaysPullImage: true
                        workingDir: "/home/jenkins/agent"

  serviceType: LoadBalancer
  loadBalancerIP: "192.168.5.241"

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce