controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"

  installPlugins:
    - kubernetes:latest
    - git:latest
    - configuration-as-code:latest
    - workflow-aggregator:latest
    - sonar:latest
    - pipeline-utility-steps:latest
    - workflow-multibranch:latest
    - hashicorp-vault-plugin:latest
    - credentials-binding:latest

  env:
    - name: VAULT_ADDR  # Vault Address for the agent
      value: "http://vault.security-tools.svc.cluster.local:8200"
    - name: SONAR_HOST_URL
      value: "http://sonarqube-sonarqube.devsecops:9000"

  extraEnv:
    - name: SONAR_TOKEN # For SonarQube plugin configuration
      valueFrom:
        secretKeyRef:
          name: jenkins-sonar-token # Kubernetes Secret name
          key: token # Key in the secret

  serviceType: LoadBalancer
  loadBalancerIP: "192.168.5.241" # Replace with your desired IP

  persistence:
    enabled: true
    size: 10Gi
    storageClass: longhorn # Replace with your storage class
    accessMode: ReadWriteOnce

  JCasC:
    configScripts:
      jenkins-auth: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin@123" # CHANGE THIS IN PRODUCTION!
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

      vault: |
        unclassified:
          hashicorpVault:
            configuration:
              engineVersion: 2
              skipSslVerification: true # Only for testing!  Use proper TLS in production.
              timeout: 60
              vaultUrl: "${VAULT_ADDR}"  # Use the environment variable

      sonar: |
        unclassified:
          sonarGlobalConfiguration:
            buildWrapperEnabled: true
            installations:
              - name: "SonarQube"
                serverUrl: "${SONAR_HOST_URL}" # Use the environment variable
                credentialsId: "sonar-token" # This will be resolved by the plugin if SONAR_TOKEN is set as env var

      clouds: |
        jenkins:
          clouds:
            - kubernetes:
                containerCap: 10
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                namespace: "devsecops"
                skipTlsVerify: true # Only for testing! Use proper TLS in production.
                jenkinsUrl: "http://jenkins.devsecops:8080"
                jenkinsTunnel: "jenkins-agent.devsecops:50000"
                templates:
                  - name: "jenkins-agent"
                    label: "jenkins-agent"
                    nodeUsageMode: NORMAL
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        alwaysPullImage: true
                        workingDir: "/home/jenkins/agent"
                        env: # Pass Vault address to the agent
                          - name: VAULT_ADDR
                            value: "http://vault.security-tools.svc.cluster.local:8200"