# tools/jenkins/values.yaml
controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"
  installPlugins:
    - kubernetes:latest
    - git:latest
    - configuration-as-code:latest
    - workflow-aggregator:latest
    - sonar:latest
    - pipeline-utility-steps:latest
    - workflow-multibranch:latest
    - hashicorp-vault-plugin:latest
    - credentials-binding:latest
  JCasC:
    configScripts:
      jenkins-auth: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin@123"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      id: "sonar-token"
                      secret: ${SONAR_TOKEN}
                      scope: GLOBAL
                      description: "SonarQube Token"
                  - string:
                      id: "vault-token"
                      secret: ${VAULT_TOKEN}
                      scope: GLOBAL
                      description: "Vault Root Token"
      vault: |
        unclassified:
          hashicorpVault:
            configuration:
              engineVersion: 2
              skipSslVerification: true
              timeout: 60
              vaultCredentialId: "vault-token"
              vaultUrl: "http://vault.security-tools.svc.cluster.local:8200"
              failIfNotFound: true
          
      sonar: |
        unclassified:
          sonarGlobalConfiguration:
            buildWrapperEnabled: true
            installations:
              - name: "SonarQube"
                serverUrl: "http://sonarqube-sonarqube.devsecops:9000"
                credentialsId: "sonar-token"
      clouds: |
        jenkins:
          clouds:
            - kubernetes:
                containerCap: 10
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                namespace: "devsecops"
                skipTlsVerify: true
                jenkinsUrl: "http://jenkins.devsecops:8080"
                jenkinsTunnel: "jenkins-agent.devsecops:50000"
                podLabels:
                  - key: "jenkins"
                    value: "slave"
                templates:
                  - name: "jenkins-agent"
                    label: "jenkins-agent"
                    nodeUsageMode: NORMAL
                    serviceAccount: "default"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        alwaysPullImage: true
                        command: ""
                        args: "^${computer.jnlpmac} ^${computer.name}"
                        ttyEnabled: false
                        workingDir: "/home/jenkins/agent"
                        privileged: false
                        runAsGroup: "1000"
                        runAsUser: "1000"
                    volumes:
                      - hostPathVolume:
                          hostPath: "/var/run/docker.sock"
                          mountPath: "/var/run/docker.sock"
                    workspaceVolume:
                      emptyDirWorkspaceVolume:
                        memory: false
                    yamlMergeStrategy: "override"
                    showRawYaml: true
                    idleMinutes: 0
                    activeDeadlineSeconds: 300
  extraEnv:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-sonar-token
          key: token
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-vault-token
          key: token
  serviceType: LoadBalancer
  loadBalancerIP: "192.168.5.241"

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteOnce