# tools/argocd/values.yaml
server:
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
  ingress:
    enabled: false

redis:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"

controller:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

repoServer:
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"